log_keep_count = 10
log_level = "debug"
log_size_mb = 1
log_to_file = false
reverse_proxy_ip = "127.0.0.1"
limit_request_seconds = 30
max_attachment_size_mb = 5.0

[mail]
smtp = ""
port = 465
user = ""
password = ""
starttls = false

[[mail.recipients]]
direction = "contact"
mails = []
